=== erc-dharma/project-documentation/schema/metadata/DHARMA_mdt_compositeArtefactDTD.dtd
<?xml version="1.0" encoding="utf-8" ?>
<!ELEMENT compositeArtefactMetadataTemplate (resourceManagement, compositeArtefactDescription)>
  <!ELEMENT resourceManagement (resourceID, metadataOrigin, metadataEditor, metadataContribution+, metadataReview+, project, corpus, metadataRights)>
    <!ELEMENT resourceID EMPTY>
    <!ATTLIST resourceID
    digitalID ID #REQUIRED
    >
    <!ELEMENT metadataOrigin (#PCDATA)>
    <!ELEMENT metadataEditor (creation+)>
      <!ELEMENT creation EMPTY>
      <!ATTLIST creation
      who CDATA #REQUIRED
      when CDATA #REQUIRED
      >
      <!-- ajouter un pointeur vers la liste des membres du projet -->
      
    <!ELEMENT metadataContribution (change)>
      <!ELEMENT change (#PCDATA)>
      <!-- ajouter un pointeur vers la liste des membres du projet -->
      <!ATTLIST change
      who CDATA #REQUIRED
      when CDATA #REQUIRED
      status CDATA #REQUIRED><!-- ajouter les valeurs possibles pour le workflow -->
      
    <!ELEMENT metadataReview EMPTY>
    <!ATTLIST metadataReview
    who CDATA #REQUIRED
    when CDATA #REQUIRED><!-- ajouter un pointeur vers la liste des membres du projet -->
    
    <!ELEMENT project (#PCDATA)>
    <!ELEMENT corpus (#PCDATA)>
    <!ELEMENT metadataRights EMPTY>
    <!ATTLIST metadataRights
    target CDATA #FIXED "CC0 1.0"
    >
<!ELEMENT compositeArtefactDescription (compositeArtefactID,material+,compositeArtefactType,decoDesc,compositeArtefactFormat,copperplateFormat,condition,compositeArtefactHistory,originPlace,discoveryPlace,preservationPlace,compositeArtefactRights,relatedResources)>
<!-- PRECISER LES CHAMPS OBLIGATOIRES OU OPTIONNELS -->
  <!ELEMENT compositeArtefactID EMPTY>
  <!ATTLIST compositeArtefactID
  idno ID #REQUIRED
  >
  <!ELEMENT material EMPTY>
  <!ATTLIST material
  value (unknown|valeur1|valeur2|...) "unknown">
  
  <!-- ajouter les valeurs des vocabulaires contrôlés d'OpenTheso -->
  <!ELEMENT compositeArtefactType EMPTY>
  <!ATTLIST compositeArtefactType
  value (unknown|valeur1|valeur2|...) "unknown"><!-- ajouter les valeurs des vocabulaires contrôlés d'OpenTheso -->
  
  <!ELEMENT decoDesc (decoration+,decorationRemarks)>
    <!ELEMENT decoration EMPTY>
    <!ATTLIST decoration
    value (none|valeur1|valeur2|...) "none">
    
    <!-- ajouter les valeurs des vocabulaires contrôlés d'OpenTheso -->
    <!ELEMENT decorationRemarks (p)>
      <!ELEMENT p (#PCDATA)>
  <!ELEMENT compositeArtefactFormat (height+,width+,diameter+,circumference+, weight+)>
    <!ELEMENT height (#PCDATA)>
    <!ATTLIST height
    unit (m|cm) "cm"
    >
    <!ELEMENT width (#PCDATA)>
    <!ATTLIST width
    unit (m|cm) "cm"
    >
    <!ELEMENT diameter (#PCDATA)>
    <!ATTLIST diameter
    unit (m|cm) "cm"
    >
    <!ELEMENT circumference (#PCDATA)>
    <!ATTLIST circumference
    unit (m|cm) "cm"
    >
    <!ELEMENT weight (#PCDATA)>
    <!ATTLIST weight
    unit (kg|g) "g"
    >
  <!ELEMENT copperplateFormat (copperplatesSetWeight,bindingRing,sealPreservation,sealingTechnique,sealHeight,sealWidth)>
    <!ELEMENT copperplatesSetWeight (#PCDATA)>
    <!ATTLIST copperplatesSetWeight
    unit (kg|g) "g"
    >
    <!ELEMENT bindingRing EMPTY>
    <!ATTLIST bindingRing
    number CDATA #REQUIRED
    >
    <!ELEMENT sealPreservation EMPTY>
    <!ATTLIST sealPreservation
    value (yes|no) "no"
    >
    <!ELEMENT sealingTechnique EMPTY>
    <!ATTLIST sealingTechnique
    value (seal_stamped_onto_body_of_plate|seal_stamped_onto_binding_ring|seal_stamped_onto_plate_projection|seal_stamped_into_other_seal|seal-like_engraving_into_artefact|unknown|not_applicable) "not_applicable"
    ><!-- liste à définir -->
    <!ELEMENT sealHeight (#PCDATA)>
    <!ATTLIST sealHeight
    unit (m|cm) "cm"
    >
    <!ELEMENT sealWidth (#PCDATA)>
    <!ATTLIST sealWidth
    unit (m|cm) "cm"
    >
  <!ELEMENT condition EMPTY>
  <!ATTLIST condition
  value (intact_and_complete|intact_and_incomplete|fragmented_and_complete|fragmented_and_incomplete|unknown) "unknown"
  >
  <!ELEMENT compositeArtefactHistory (p)>
    <!--<!ELEMENT p (#PCDATA)>-->
  <!ELEMENT originPlace (originPlaceName,originPlaceID,originPlaceRemarks)>
    <!ELEMENT originPlaceName (#PCDATA)>
    <!ELEMENT originPlaceID EMPTY>
    <!ATTLIST originPlaceID
    idno ID #REQUIRED
    >
    <!ELEMENT originPlaceRemarks (p)>
      <!--<!ELEMENT p (#PCDATA)>-->
  <!ELEMENT discoveryPlace (discoveryPlaceName,discoveryPlaceID,discoveryCoordinates,discoveryEvents+)>
    <!ELEMENT discoveryPlaceName (#PCDATA)>
    <!ELEMENT discoveryPlaceID EMPTY>
    <!ATTLIST discoveryPlaceID
    idno ID #REQUIRED
    >
    <!ELEMENT discoveryCoordinates (#PCDATA)>
    <!ELEMENT discoveryEvents (p)>
    <!-- liste à revoir -->
    <!ATTLIST discoveryEvents 
    type (excavation|find|survey|purchase|unknown) "unknown"
    when CDATA #IMPLIED
    >
      <!--<!ELEMENT p (#PCDATA)>-->
  <!ELEMENT preservationPlace (preservationPlaceName,inventoryNumber+,preservationPlaceID,preservationCoordinates,inSituStatus,preservationEvents)>
    <!ELEMENT preservationPlaceName (#PCDATA)>
    <!ELEMENT inventoryNumber (#PCDATA)>
    <!ELEMENT preservationPlaceID EMPTY>
    <!ATTLIST preservationPlaceID
    idno ID #REQUIRED
    >
    <!ELEMENT preservationCoordinates (#PCDATA)>
    <!ELEMENT inSituStatus EMPTY>
    <!ATTLIST inSituStatus
    value (yes | no) "no"
    >
    <!ELEMENT preservationEvents (p)>
    <!-- liste à revoir -->
    <!ATTLIST preservationEvents
    type (acquisition|move|destruction) "move"
    when CDATA #IMPLIED
    >
      <!--<!ELEMENT p (#PCDATA)>-->
  <!ELEMENT compositeArtefactRights (governmentalHolder,institutionalHolder,compositeArtefactDistributionRights)>
    <!ELEMENT governmentalHolder (#PCDATA)>
    <!ELEMENT institutionalHolder (#PCDATA)>
    <!ELEMENT compositeArtefactDistributionRights EMPTY>
    <!ATTLIST compositeArtefactDistributionRights
    target CDATA #FIXED "All rights reserved"
    >
  <!ELEMENT relatedResources (artefactID+,textID+,surrogateID+,imageID+)>
    <!ELEMENT artefactID EMPTY>
    <!ATTLIST artefactID
    idno ID #REQUIRED
    >
    <!ELEMENT textID EMPTY>
    <!ATTLIST textID
    idno ID #REQUIRED
    >
    <!ELEMENT surrogateID EMPTY>
    <!ATTLIST surrogateID
    idno ID #REQUIRED
    >
    <!ELEMENT imageID EMPTY>
    <!ATTLIST imageID
    idno ID #REQUIRED
    >

=== erc-dharma/project-documentation/templates/metadata/DHARMA_mdt_compositeArtefactTemplate_v01.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE compositeArtefactMetadataTemplate SYSTEM "DHARMA_mdt_compositeArtefactDTD.dtd">
<compositeArtefactMetadataTemplate>
<resourceManagement>
	<resourceID digitalID=""/>
	<metadataOrigin></metadataOrigin>
	<metadataEditor>
		<creation who="" when=""/><!-- may be repeated -->
	</metadataEditor>
	<metadataContribution>
		<change who="" when="" status=""></change><!-- may be repeated -->
	</metadataContribution>
	<metadataReview who="" when=""/><!-- may be repeated -->
	<project></project>
	<corpus></corpus>
	<metadataRights target=""/>
</resourceManagement>
	<compositeArtefactDescription>
  <compositeArtefactID idno=""/>
  <material value=""/><!-- may be repeated -->
  <compositeArtefactType value=""/><!-- may be repeated -->
  <decoDesc>
		<decoration value=""/><!-- may be repeated -->
    <decorationRemarks><p></p></decorationRemarks>
  </decoDesc>
  <compositeArtefactFormat>
    <height unit=""></height>
    <width unit=""></width>
    <diameter unit=""></diameter>
    <circumference unit=""></circumference>
		<weight unit=""></weight>
  </compositeArtefactFormat>
	<copperplateFormat><!-- description of a set of copper-plates only -->
		<copperplatesSetWeight unit=""></copperplatesSetWeight>
		<bindingRing number=""/>
		<sealPreservation value=""/><!-- only if the seal is on the binding ring -->
		<sealingTechnique value=""/>
		<sealHeight unit=""></sealHeight>
		<sealWidth unit=""></sealWidth>
	</copperplateFormat>
	<condition value=""/>
	<compositeArtefactHistory><p></p></compositeArtefactHistory>
	<originPlace>
		<originPlaceName></originPlaceName>
		<originPlaceID idno=""/>
		<originPlaceRemarks><p></p></originPlaceRemarks>
	</originPlace>
	<discoveryPlace>
		<discoveryPlaceName></discoveryPlaceName>
		<discoveryPlaceID idno=""/>
		<discoveryCoordinates></discoveryCoordinates>
		<discoveryEvents type="" when=""><p></p></discoveryEvents>
	</discoveryPlace>
	<preservationPlace>
		<preservationPlaceName></preservationPlaceName>
		<inventoryNumber></inventoryNumber>
		<preservationPlaceID idno=""/>
		<preservationCoordinates></preservationCoordinates>
		<inSituStatus value=""/>
		<preservationEvents when="" type=""><p></p></preservationEvents>
	</preservationPlace>
	<compositeArtefactRights>
		<governmentalHolder></governmentalHolder>
		<institutionalHolder></institutionalHolder>
		<compositeArtefactDistributionRights target=""/>
	</compositeArtefactRights>
	<relatedResources>
		<artefactID idno=""/><!-- may be repeated -->
		<textID idno=""/><!-- may be repeated -->
		<surrogateID idno=""/><!-- may be repeated -->
		<imageID idno=""/><!-- may be repeated -->
	</relatedResources>
</compositeArtefactDescription>
</compositeArtefactMetadataTemplate>
