=== erc-dharma/project-documentation/schema/metadata/DHARMA_mdt_artefactDTD.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT artefactMetadataTemplate (resourceManagement, artefactDescription)>
  <!ELEMENT resourceManagement (resourceID, metadataOrigin, metadataEditor, metadataContribution+, metadataReview+, project, corpus, metadataRights)>
  <!ELEMENT resourceID EMPTY>
  <!ATTLIST resourceID
  digitalID ID #REQUIRED
  >
    <!ELEMENT metadataOrigin (#PCDATA)>
    <!ELEMENT metadataEditor (creation+)>
      <!ELEMENT creation EMPTY>

      <!ATTLIST creation
      who CDATA #REQUIRED
     when CDATA #REQUIRED
      >
      <!-- ajouter un pointeur vers la liste des membres du projet -->
    <!ELEMENT metadataContribution (change+)>
      <!ELEMENT change (#PCDATA)>
      <!ATTLIST change
      who CDATA #REQUIRED><!-- ajouter un pointeur vers la liste des membres du projet -->
      <!ATTLIST change 
      when CDATA #REQUIRED
    status CDATA #REQUIRED><!-- ajouter les valeurs possibles pour le workflow -->
       
    <!ELEMENT metadataReview EMPTY>
    <!ATTLIST metadataReview
    who CDATA #REQUIRED
    when CDATA #REQUIRED>
    
    <!ELEMENT project (#PCDATA)>
    <!ELEMENT corpus (#PCDATA)>
    <!ELEMENT metadataRights EMPTY>
    <!ATTLIST metadataRights
    target CDATA #FIXED "CC0 1.0"
    >
<!ELEMENT artefactDescription (artefactID,compositeArtefactID,material+,artefactType+,decoDesc,artefactFormat,lettering,copperplateFormat?,condition,artefactHistory,originPlace,discoveryPlace,preservationPlace,artefactRights,relatedResources)>
<!-- AJ: changement de statut pour materiel-->
<!-- PRECISER LES CHAMPS OBLIGATOIRES OU OPTIONNELS -->
  <!ELEMENT artefactID EMPTY>
  <!ATTLIST artefactID
  idno ID #REQUIRED
  >
  <!ELEMENT compositeArtefactID EMPTY>
  <!ATTLIST compositeArtefactID
  idno ID #IMPLIED
  >
  <!ELEMENT material EMPTY>
  <!-- AJ: l'occurence ne peut pas être déclaré pour materiel sur l'élément lui-même. Il faut le déclarer lorsqu'il est l'enfant. Donc materiel+ devient materiel-->
  <!ATTLIST material value (unknown|valeur1|valeur2|...) "unknown">
  <!-- ajouter les valeurs des vocabulaires contrôlés d'OpenTheso -->

    
  <!ELEMENT artefactType EMPTY>
  <!--AJ:je bouge la déclarartion de l'occurence.  -->
  <!ATTLIST artefactType
  value (unknown|valeur1|valeur2|...) "unknown">
  <!-- ajouter les valeurs des vocabulaires contrôlés d'OpenTheso -->
  
  <!ELEMENT decoDesc (decoration+,decorationRemarks)>
    <!ELEMENT decoration EMPTY>
    <!ATTLIST decoration
    value (none|valeur1|valeur2|...) "none"><!-- ajouter les valeurs des vocabulaires contrôlés d'OpenTheso -->
    
    <!ELEMENT decorationRemarks (p?)>
      <!ELEMENT p (#PCDATA)>
      
  <!ELEMENT artefactFormat (height+,width+,diameter+,circumference)>
    <!ELEMENT height (#PCDATA)>
    <!ATTLIST height 
    unit (m|cm) "cm">
    
    <!ELEMENT width (#PCDATA)>
    <!ATTLIST width 
    unit (m|cm) "cm">
    
    <!ELEMENT diameter (#PCDATA)>
    <!ATTLIST diameter 
    unit (m|cm) "cm"> 
    
    <!ELEMENT circumference (#PCDATA)>
    <!ATTLIST circumference 
    unit (m|cm) "cm"> 
    
  <!ELEMENT lettering (letteringTechnique,textHeight+,textWidth+,linesNumber,glyphHeight+,glyphWidth+,letteringRemarks)>
    <!ELEMENT letteringTechnique EMPTY>
    <!ATTLIST letteringTechnique 
    value (engraved | relief | painted | unknown) "unknown"><!-- liste à revoir -->
    
    <!ELEMENT textHeight (#PCDATA)>
    <!ATTLIST textHeight 
    unit (m|cm) "cm"> 
    
    <!ELEMENT textWidth (#PCDATA)>
   <!ATTLIST textWidth 
   unit (m|cm) "cm">
    
    <!ELEMENT linesNumber (#PCDATA)>
    <!ELEMENT glyphHeight (#PCDATA)>
   <!ATTLIST glyphHeight 
    unit (m|cm) "cm">
    
    <!ELEMENT glyphWidth (#PCDATA)>
      <!ATTLIST glyphWidth 
     unit (m|cm) "cm">
    
    <!ELEMENT letteringRemarks (p)>
      <!--<!ELEMENT p (#PCDATA)>-->
  <!ELEMENT copperplateFormat (copperplateWeight, copperplateWeightOther?, bindingHole, sealPreservation, sealingTechnique, sealHeight, sealWidth)>
    <!ELEMENT copperplateWeight (#PCDATA)>
    <!ATTLIST copperplateWeight
    unit CDATA #REQUIRED
    >
    <!ELEMENT copperplateWeightOther (#PCDATA)>
    <!-- AJ: il n'y a pas copperplateWeightOther dans le template seulement copperplateWeight -->
    <!ATTLIST copperplateWeightOther 
     unit (kg|g) "g">
    
    <!ELEMENT bindingHole EMPTY>
    <!ATTLIST bindingHole
    number CDATA #REQUIRED>
    
    <!ELEMENT sealPreservation EMPTY>
    <!ATTLIST sealPreservation
    value (yes|no) "yes">
    
    <!ELEMENT sealingTechnique EMPTY>
   <!ATTLIST sealingTechnique value (seal_stamped_onto_body_of_plate|seal_stamped_onto_binding_ring|seal_stamped_onto_plate_projection|seal_stamped_into_other_seal|seal-like_engraving_into_artefact|unknown|not_applicable) "not_applicable"><!-- liste à définir -->
    
    <!ELEMENT sealHeight (#PCDATA)>
    <!ATTLIST sealHeight 
    unit (m | cm) "cm">
    
    <!ELEMENT sealWidth (#PCDATA)>
    <!ATTLIST sealWidth 
    unit (m | cm) "cm">
    
  <!ELEMENT condition EMPTY>
  <!ATTLIST condition
  value (intact_and_complete|intact_and_incomplete|fragmented_and_complete|fragmented_and_incomplete|unknown) "unknown"> <!-- liste à revoir -->
  
  <!ELEMENT artefactHistory (p)>
   <!-- <!ELEMENT p (#PCDATA)>-->
    
  <!ELEMENT originPlace (originPlaceName,originPlaceID,originPlaceRemarks)>
    <!ELEMENT originPlaceName (#PCDATA)>
    <!ELEMENT originPlaceID EMPTY>
    <!ATTLIST originPlaceID
    idno ID #REQUIRED>
    
    <!ELEMENT originPlaceRemarks (p)>
  <!--    <!ELEMENT p (#PCDATA)>-->
  <!ELEMENT discoveryPlace (discoveryPlaceName,discoveryPlaceID,discoveryCoordinates,discoveryEvents)>
    <!ELEMENT discoveryPlaceName (#PCDATA)>
    <!ELEMENT discoveryPlaceID EMPTY>
    <!ATTLIST discoveryPlaceID
    idno ID #REQUIRED>
    
    <!ELEMENT discoveryCoordinates (#PCDATA)>
    <!ELEMENT discoveryEvents (p)>
    <!ATTLIST discoveryEvents
    type (excavation|find|survey|purchase|unknown) "unknown"
    when CDATA #REQUIRED>
    <!-- liste à revoir -->
    
      <!--<!ELEMENT p (#PCDATA)>-->
  <!ELEMENT preservationPlace (preservationPlaceName,inventoryNumber+,preservationPlaceID,preservationCoordinates,inSituStatus?,preservationEvents)>
    <!ELEMENT preservationPlaceName (#PCDATA)>
    <!ELEMENT inventoryNumber (#PCDATA)>
    <!ELEMENT preservationPlaceID EMPTY>
    <!ATTLIST preservationPlaceID
    idno ID #REQUIRED
    >
    <!ELEMENT preservationCoordinates (#PCDATA)>
    <!ELEMENT inSituStatus EMPTY>
    <!ATTLIST inSituStatus
    value (yes|no) "no">
    
    <!ELEMENT preservationEvents (p)>
    <!ATTLIST preservationEvents
    type (acquisition|move|destruction) "move"
     when CDATA #REQUIRED>
     
    <!--  <!ELEMENT p (#PCDATA)>-->
  <!ELEMENT artefactRights (governmentalHolder,institutionalHolder,artefactDistributionRights)>
    <!ELEMENT governmentalHolder (#PCDATA)>
    <!ELEMENT institutionalHolder (#PCDATA)>
    <!ELEMENT artefactDistributionRights EMPTY>
    <!ATTLIST artefactDistributionRights
    target CDATA  #FIXED "All rights reserved">

  <!ELEMENT relatedResources (textID+,surrogateID+,imageID+)>
    <!ELEMENT textID EMPTY>
    <!ATTLIST textID
    idno ID #REQUIRED
    >
    <!ELEMENT surrogateID EMPTY>
    <!ATTLIST surrogateID
    idno ID #REQUIRED
    >
    <!ELEMENT imageID EMPTY>
    <!ATTLIST imageID
    idno ID #REQUIRED>

=== erc-dharma/project-documentation/templates/metadata/DHARMA_mdt_artefactTemplate_v02.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE artefactMetadataTemplate SYSTEM "DHARMA_mdt_artefactDTD.dtd">
<artefactMetadataTemplate>
<resourceManagement>
	<resourceID digitalID=""/>
	<metadataOrigin></metadataOrigin>
	<metadataEditor>
		<creation who="" when=""/><!-- may be repeated -->
	</metadataEditor>
	<metadataContribution>
		<change who="" when="" status=""></change><!-- may be repeated -->
	</metadataContribution>
	<metadataReview who="" when=""/><!-- may be repeated -->
	<project></project>
	<corpus></corpus>
	<metadataRights target=""/>
</resourceManagement>
<artefactDescription>
  <artefactID idno=""/>
  <compositeArtefactID idno=""/>
  <material value=""/><!-- may be repeated -->
  <artefactType value=""/><!-- may be repeated -->
  <decoDesc>
		<decoration value=""/><!-- may be repeated -->
    <decorationRemarks><p></p></decorationRemarks>
  </decoDesc>
  <artefactFormat>
    <height unit=""></height>
    <width unit=""></width>
    <diameter unit=""></diameter>
    <circumference unit=""></circumference>
  </artefactFormat>
	<lettering>
		<letteringTechnique value=""/>
		<textHeight unit=""></textHeight>
		<textWidth unit=""></textWidth>
		<linesNumber></linesNumber>
		<glyphHeight unit=""></glyphHeight>
		<glyphWidth unit=""></glyphWidth>
		<letteringRemarks><p></p></letteringRemarks>
	</lettering>
	<copperplateFormat>
		<copperplateWeight unit=""></copperplateWeight>
		<copperplateWeightOther unit=""></copperplateWeightOther>
		<bindingHole number=""/>
		<sealPreservation value=""/><!-- only if the seal is on the plate, in case of a set of copper-plates, all the information about the seal has to be describded at the composite artefact level -->
		<sealingTechnique value=""/>
		<sealHeight unit=""></sealHeight>
		<sealWidth unit=""></sealWidth>
	</copperplateFormat>
	<condition value=""/>
	<artefactHistory><p></p></artefactHistory>
	<originPlace>
		<originPlaceName></originPlaceName>
		<originPlaceID idno=""/>
		<originPlaceRemarks><p></p></originPlaceRemarks>
	</originPlace>
	<discoveryPlace>
		<discoveryPlaceName></discoveryPlaceName>
		<discoveryPlaceID idno=""/>
		<discoveryCoordinates></discoveryCoordinates>
		<discoveryEvents type="" when=""><p></p></discoveryEvents>
	</discoveryPlace>
	<preservationPlace>
		<preservationPlaceName></preservationPlaceName>
		<inventoryNumber></inventoryNumber><!-- may be repeated -->
		<preservationPlaceID idno=""/>
		<preservationCoordinates></preservationCoordinates>
		<inSituStatus value=""/>
		<preservationEvents when="" type=""><p></p></preservationEvents>
	</preservationPlace>
	<artefactRights>
		<governmentalHolder></governmentalHolder>
		<institutionalHolder></institutionalHolder>
		<artefactDistributionRights target=""/>
	</artefactRights>
	<relatedResources>
		<textID idno=""/><!-- may be repeated -->
		<surrogateID idno=""/><!-- may be repeated -->
		<imageID idno=""/><!-- may be repeated -->
	</relatedResources>
</artefactDescription>
</artefactMetadataTemplate>

=== erc-dharma/project-documentation/templates/metadata/DHARMA_mdt_artefactTemplate_v01.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE artefactMetadataTemplate SYSTEM "DHARMA_mdt_artefactDTD.dtd"[]>
<artefactMetadataTemplate>
<resourceManagement>
	<resourceID digitalID=""></resourceID>
	<metadataOrigin></metadataOrigin>
	<metadataEditor>
		<creation who="" when=""/>
	</metadataEditor>
	<metadataContribution>
		<change who="" when="" status=""></change>
		<metadataReview who="" when=""/>
	</metadataContribution>
	<project></project>
	<corpus></corpus>
	<metadataRights target=""><p></p></metadataRights>
</resourceManagement>
<artefactDescription>
  <artefactID idno=""></artefactID>
  <compositeArtefactID idno=""/>
  <material ref="" value=""/>
  <artefactType ref="" value=""/>
  <decoDesc>
		<decoration ref="" value=""/>
    <decorationRemarks><p></p></decorationRemarks>
  </decoDesc>
  <artefactFormat>
    <height unit=""></height>
    <width unit=""></width>
    <diameter unit=""></diameter>
    <circumference unit=""></circumference>
  </artefactFormat>
	<lettering>
		<letteringTechnique ref="" value=""/>
		<textHeight unit=""></textHeight>
		<textWidth unit=""></textWidth>
		<linesNumber></linesNumber>
		<glyphHeight unit=""></glyphHeight>
		<glyphWidth unit=""></glyphWidth>
		<letteringRemarks><p></p></letteringRemarks>
	</lettering>
	<copperplateFormat><!-- description of a single copper-plate, the set is describded in separate file for composite artefact -->
		<copperplateWeight unit=""></copperplateWeight>
		<copperplateWeightOther></copperplateWeightOther>
		<bindingHole number=""/>
		<sealPreservation value=""/><!-- only if the seal is on the copper-plate -->
		<sealingTechnique ref="" value=""/>
		<sealHeight unit=""></sealHeight>
		<sealWidth unit=""></sealWidth>
	</copperplateFormat>
	<condition ref="" value=""/>
	<artefactHistory type="" when=""><p></p></artefactHistory>
	<originPlace>
		<originPlaceName></originPlaceName>
		<originPlaceID idno=""/>
		<originPlaceRemarks><p></p></originPlaceRemarks>
	</originPlace>
	<discoveryPlace>
		<discoveryPlaceName></discoveryPlaceName>
		<discoveryPlaceID idno=""/>
		<discoveryCoordinates></discoveryCoordinates>
		<discoveryEvents when="" type=""><p></p></discoveryEvents>
	</discoveryPlace>
	<preservationPlace>
		<preservationPlaceName></preservationPlaceName>
		<inventoryNumber></inventoryNumber>
		<preservationPlaceID idno=""/>
		<preservationCoordinates></preservationCoordinates>
		<inSituStatus value=""/>
		<preservationEvents when="" type=""><p></p></preservationEvents>
	</preservationPlace>
	<artefactRights>
		<governmentalHolder></governmentalHolder>
		<institutionalHolder></institutionalHolder>
		<artefactDistributionRights target=""/>
	</artefactRights>
	<relatedResources>
		<textID idno=""/>
		<surrogateID idno=""/>
		<imageID idno=""/>
	</relatedResources>
</artefactDescription>
</artefactMetadataTemplate>
